apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: soldier
  name: soldier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soldier
  template:
    metadata:
      labels:
        app: soldier
    spec:
      containers:
      - image: soldier:v1
        name: soldier
        resources: {}